Repository spharos-1th-project-moa/BE-MEETING, pull requests merged in 2023-11, with the labels that each got.

#15 feat: 모임 전반적인 네이밍 수정, 참여가능회사그룹 저장 데이터 수정, MeetingStatus DELETE 추가
  src/main/java/com/moa/meeting/adaptor/infrastructure/mysql/converter/BaseEnumConverter.java
  src/main/java/com/moa/meeting/adaptor/infrastructure/mysql/entity/MeetingEntity.java
  src/main/java/com/moa/meeting/adaptor/infrastructure/mysql/persistance/MeetingAdaptor.java
  src/main/java/com/moa/meeting/adaptor/web/request/MeetingCreateReq.java
  src/main/java/com/moa/meeting/application/ports/in/MeetingUseCase.java
  src/main/java/com/moa/meeting/application/ports/out/dto/MeetingGetDto.java
  src/main/java/com/moa/meeting/application/service/MeetingService.java
  src/main/java/com/moa/meeting/domain/Meeting.java
  src/main/java/com/moa/meeting/domain/enums/CanParticipateGender.java
  src/main/java/com/moa/meeting/domain/enums/MeetingStatus.java
Labels: enhancement

#19 feat: 모임 간단 정보 조회
  src/main/java/com/moa/meeting/application/MeetingService.java
  src/main/java/com/moa/meeting/application/MeetingServiceImpl.java
  src/main/java/com/moa/meeting/dto/MeetingSimpleGetDto.java
  src/main/java/com/moa/meeting/presentation/MeetingController.java
  src/main/java/com/moa/meeting/vo/response/MeetingSimpleResponse.java
Labels: documentation

#21 [refact] 모임설명길이 늘리기
  src/main/java/com/moa/meeting/domain/Meeting.java
Labels: invalid

#24 fix: json serialize 에러 해결 시도
  .github/workflows/ci.yml
  src/main/java/com/moa/meeting/dto/CategoryMeetingCreateDto.java
  src/main/java/com/moa/meeting/infrastructure/kafka/producer/KafkaTestController.java
  src/main/java/com/moa/meeting/infrastructure/kafka/producer/MeetingCreateProducer.java
Labels: bug

#25 fix: kafka yml 탭 수정
  .github/workflows/ci.yml
Labels: bug

#26 fix: kafka yml 탭 수정
  src/main/resources/application-prod.yml
Labels: bug

#28 feat: 모임 생성시 kafka로 이벤트 전송
  src/main/java/com/moa/meeting/application/MeetingServiceImpl.java
  src/main/java/com/moa/meeting/dto/CategoryMeetingCreateDto.java
  src/main/java/com/moa/meeting/dto/MeetingCreateDto.java
  src/main/java/com/moa/meeting/infrastructure/kafka/producer/KafkaTestController.java
  src/main/java/com/moa/meeting/presentation/MeetingController.java
  src/main/java/com/moa/meeting/vo/request/MeetingCreateRequest.java
Labels: enhancement

#30 feat: 카프카 모임 참여 이벤트 consumer
  src/main/java/com/moa/meeting/domain/enums/ApplicationStatus.java
  src/main/java/com/moa/meeting/dto/kafka/ParticipantApplicationUpdateEventDto.java
  src/main/java/com/moa/meeting/infrastructure/kafka/consumer/ParticipateStatusUpdateEventConsumer.java
  src/main/resources/application-prod.yml
Labels: enhancement

#33 fix: kafka 참여상태 update consumer ClassCastException에러 수정
  .github/workflows/ci.yml
  src/main/java/com/moa/meeting/infrastructure/kafka/consumer/ParticipateStatusUpdateEventConsumer.java
Labels: bug

#35 feat: 모임 정보 update 이벤트 consumer에 service 추가
  src/main/java/com/moa/meeting/infrastructure/kafka/consumer/ParticipateStatusUpdateEventConsumer.java
Labels: enhancement

#36 fix: object to boolean 변환 에러 수정
  .github/workflows/ci.yml
  src/main/java/com/moa/meeting/infrastructure/kafka/consumer/ParticipateStatusUpdateEventConsumer.java
Labels: bug

#39 feat: 모임 취소 이벤트 producer
  src/main/java/com/moa/meeting/dto/kafka/MeetingCancelEventDto.java
  src/main/java/com/moa/meeting/infrastructure/kafka/producer/MeetingCancelProducer.java
Labels: enhancement

#40 feat: 모임 정보 update producer
  src/main/java/com/moa/meeting/infrastructure/kafka/producer/MeetingUpdateProducer.java
Labels: enhancement

#41 feat: 모임 상세설명 chatgpt 생성
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/moa/BeMeetingApplication.java
  src/main/java/com/moa/global/config/FeignConfig.java
  src/main/java/com/moa/meeting/application/DescriptionGenerationService.java
  src/main/java/com/moa/meeting/application/DescriptionGenerationServiceImpl.java
  src/main/java/com/moa/meeting/client/ChatGPTClient.java
  src/main/java/com/moa/meeting/client/vo/ChatGPTMessageItemRequest.java
  src/main/java/com/moa/meeting/client/vo/ChatGPTRequest.java
  src/main/java/com/moa/meeting/client/vo/ChatGptMessageDto.java
  src/main/java/com/moa/meeting/client/vo/ChatGptResponse.java
  src/main/java/com/moa/meeting/presentation/DescriptionGenerationController.java
  src/main/java/com/moa/meeting/vo/request/DescreptionGenerationRequest.java
  src/main/resources/application.yml
Labels: enhancement

#42 feat: 모임 생성시 kafka 대신 동기통신 (feign client) 하는 API
  src/main/java/com/moa/meeting/application/MeetingFeignService.java
  src/main/java/com/moa/meeting/client/CategoryClient.java
  src/main/java/com/moa/meeting/presentation/MeetingFeignController.java
Labels: enhancement
